name: Deploy Monitoring Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    # GANTI INI: Dari 'ubuntu-latest' jadi 'self-hosted'
    runs-on: self-hosted 
    
    steps:
      - name: Update and Rebuild
        run: |
          cd /home/fikri/project/monitoring_server
          git pull origin main
          # Pakai path Go yang sudah terinstall di server (cek pakai 'which go')
          go build -o monitoring_app .
          # Jalankan restart (sekarang harusnya tanpa password)
          sudo systemctl restart monitoring_server